/**
 * @typedef {Object} Product
 * @property {number} id - Идентификатор продукта.
 * @property {string} title - Название продукта.
 * @property {number} price - Цена продукта.
 * @property {string} image - URL изображения продукта.
 * @property {Characteristic} characteristics - Характеристики продукта.
 */
/**
 * @typedef {Object} Characteristic
 * @property {string} country - Страна производства.
 * @property {string} brand - Бренд.
 * @property {string} dossage - Дозировка.
 * @property {string} releaseForm - Форма выпуска.
 * @property {string} storageTemperature - Температура хранения.
 * @property {number} quantityPerPackage - Количество в упаковке.
 * @property {string} expirationDate - Срок годности.
 * @property {boolean} isByPrescription - Требуется ли рецепт.
 * @property {string} manufacturer - Производитель.
 */
/**
 * @type {Product[]}
 */
export const data = [
  {
    id: 1,
    title:
      "Цефуроксим 750 мг порошок для приготовления раствора для инъекций флакон 1 шт",
    price: 26.42,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Беларусь",
      brand: "Белмедпрепараты",
      dossage: "750 мг",
      releaseForm: "Порошок для приготовления раствора для инъекций",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 6,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Байер АГ",
    },
  },
  {
    id: 2,
    title: "Амоксициллин 500 мг капсулы 20 шт",
    price: 15.99,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 3,
    title:
      "Цефтриаксон 1 г порошок для приготовления раствора для инъекций 1 шт",
    price: 30.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Беларусь",
      brand: "Белмедпрепараты",
      dossage: "1 г",
      releaseForm: "Порошок для приготовления раствора для инъекций",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 1,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Байер АГ",
    },
  },
  {
    id: 4,
    title: "Парацетамол 500 мг таблетки 10 шт",
    price: 5.5,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 10,
      expirationDate: "4 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 5,
    title: "Ибупрофен 400 мг таблетки 20 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "400 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 6,
    title: "Кларитромицин 250 мг таблетки 14 шт",
    price: 18.75,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "250 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 14,
      expirationDate: "3 года",
      isByPrescription: true,
      manufacturer: "Синтез",
    },
  },
  {
    id: 7,
    title: "Левофлоксацин 500 мг таблетки 10 шт",
    price: 22.3,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 10,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 8,
    title: "Метронидазол 500 мг таблетки 20 шт",
    price: 9.99,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 9,
    title: "Диклофенак 100 мг суппозитории 12 шт",
    price: 14.5,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "100 мг",
      releaseForm: "Суппозитории",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 12,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 10,
    title: "Сумамед 500 мг таблетки 6 шт",
    price: 35.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Беларусь",
      brand: "Белмедпрепараты",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 6,
      expirationDate: "3 года",
      isByPrescription: true,
      manufacturer: "Байер АГ",
    },
  },
  {
    id: 11,
    title: "Флуконазол 150 мг капсулы 1 шт",
    price: 7.5,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "150 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 1,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 12,
    title: "Омепразол 20 мг таблетки 14 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "20 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 14,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 13,
    title: "Аторвастатин 20 мг таблетки 30 шт",
    price: 25.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "20 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 14,
    title: "Лизиноприл 10 мг таблетки 20 шт",
    price: 18.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "10 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: true,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 15,
    title: "Метопролол 50 мг таблетки 30 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "50 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: true,
      manufacturer: "Синтез",
    },
  },
  {
    id: 16,
    title: "Гидрохлоротиазид 12.5 мг таблетки 20 шт",
    price: 8.5,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "12.5 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 17,
    title: "Симвастатин 20 мг таблетки 30 шт",
    price: 22.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "20 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 18,
    title: "Кетопрофен 100 мг таблетки 20 шт",
    price: 11.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "100 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 19,
    title: "Трамадол 50 мг капсулы 10 шт",
    price: 30.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "50 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 10,
      expirationDate: "2 года",
      isByPrescription: true,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 20,
    title: "Фенобарбитал 100 мг таблетки 20 шт",
    price: 5.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "100 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "4 года",
      isByPrescription: true,
      manufacturer: "Синтез",
    },
  },
  {
    id: 21,
    title: "Клонидин 0.15 мг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "0.15 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: true,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 22,
    title: "Аспирин 500 мг таблетки 20 шт",
    price: 6.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "4 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 23,
    title: "Кальций Д3 500 мг таблетки 30 шт",
    price: 10.5,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 24,
    title: "Глюкозамин 500 мг капсулы 60 шт",
    price: 25.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 25,
    title: "Магний Б6 100 мг таблетки 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Фармстандарт",
      dossage: "100 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Фармстандарт",
    },
  },
  {
    id: 26,
    title: "Омега-3 1000 мг капсулы 30 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "1000 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 27,
    title: "Витамин C 1000 мг таблетки 20 шт",
    price: 8.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "1000 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 20,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 28,
    title: "Витамин D3 2000 МЕ капсулы 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "2000 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 29,
    title: "Куркумин 500 мг капсулы 60 шт",
    price: 18.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 30,
    title: "Гинкго Билоба 120 мг капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "120 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 31,
    title: "Эхинацея 300 мг капсулы 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "300 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 32,
    title: "Л-карнитин 500 мг капсулы 60 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 33,
    title: "Коэнзим Q10 100 мг капсулы 30 шт",
    price: 25.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "100 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 34,
    title: "Мелатонин 3 мг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "3 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 35,
    title: "Пробиотики 10 млрд КОЕ капсулы 30 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "10 млрд КОЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 36,
    title: "Цинк 15 мг таблетки 30 шт",
    price: 8.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "15 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 37,
    title: "Магний 250 мг таблетки 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "250 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 38,
    title: "Кальций 500 мг таблетки 30 шт",
    price: 9.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 39,
    title: "Витамин E 400 МЕ капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "400 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 40,
    title: "Витамин B12 1000 мкг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "1000 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 41,
    title: "Витамин A 10000 МЕ капсулы 30 шт",
    price: 14.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "10000 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 42,
    title: "Фолиевая кислота 400 мкг таблетки 30 шт",
    price: 7.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "400 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 43,
    title: "Куркумин 500 мг капсулы 60 шт",
    price: 18.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 44,
    title: "Гинкго Билоба 120 мг капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "120 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 45,
    title: "Эхинацея 300 мг капсулы 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "300 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 46,
    title: "Л-карнитин 500 мг капсулы 60 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 47,
    title: "Коэнзим Q10 100 мг капсулы 30 шт",
    price: 25.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "100 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 48,
    title: "Мелатонин 3 мг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Синтез",
      dossage: "3 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Синтез",
    },
  },
  {
    id: 49,
    title: "Пробиотики 10 млрд КОЕ капсулы 30 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Россия",
      brand: "Экофарм",
      dossage: "10 млрд КОЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Экофарм",
    },
  },
  {
    id: 50,
    title: "Цинк 15 мг таблетки 30 шт",
    price: 8.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Германия",
      brand: "Bayer",
      dossage: "15 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Bayer AG",
    },
  },
  {
    id: 51,
    title: "Магний 250 мг таблетки 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Франция",
      brand: "Pierre Fabre",
      dossage: "250 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Pierre Fabre",
    },
  },
  {
    id: 52,
    title: "Кальций 500 мг таблетки 30 шт",
    price: 9.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Италия",
      brand: "Chiesi",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Chiesi Farmaceutici",
    },
  },
  {
    id: 53,
    title: "Витамин E 400 МЕ капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Испания",
      brand: "Almirall",
      dossage: "400 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Almirall",
    },
  },
  {
    id: 54,
    title: "Витамин B12 1000 мкг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Швеция",
      brand: "AstraZeneca",
      dossage: "1000 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "AstraZeneca",
    },
  },
  {
    id: 55,
    title: "Витамин A 10000 МЕ капсулы 30 шт",
    price: 14.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Нидерланды",
      brand: "DSM",
      dossage: "10000 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "DSM Nutritional Products",
    },
  },
  {
    id: 56,
    title: "Фолиевая кислота 400 мкг таблетки 30 шт",
    price: 7.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Австрия",
      brand: "Sandoz",
      dossage: "400 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Sandoz",
    },
  },
  {
    id: 57,
    title: "Куркумин 500 мг капсулы 60 шт",
    price: 18.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Польша",
      brand: "Polpharma",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Polpharma",
    },
  },
  {
    id: 58,
    title: "Гинкго Билоба 120 мг капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Чехия",
      brand: "Zentiva",
      dossage: "120 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Zentiva",
    },
  },
  {
    id: 59,
    title: "Эхинацея 300 мг капсулы 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Словакия",
      brand: "Herbapol",
      dossage: "300 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Herbapol",
    },
  },
  {
    id: 60,
    title: "Л-карнитин 500 мг капсулы 60 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Бельгия",
      brand: "Omega Pharma",
      dossage: "500 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 60,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Omega Pharma",
    },
  },
  {
    id: 61,
    title: "Коэнзим Q10 100 мг капсулы 30 шт",
    price: 25.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Ирландия",
      brand: "NutraBlast",
      dossage: "100 мг",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "NutraBlast",
    },
  },
  {
    id: 62,
    title: "Мелатонин 3 мг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Финляндия",
      brand: "Orion",
      dossage: "3 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Orion Pharma",
    },
  },
  {
    id: 63,
    title: "Пробиотики 10 млрд КОЕ капсулы 30 шт",
    price: 20.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Дания",
      brand: "Novo Nordisk",
      dossage: "10 млрд КОЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Novo Nordisk",
    },
  },
  {
    id: 64,
    title: "Цинк 15 мг таблетки 30 шт",
    price: 8.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Норвегия",
      brand: "Norsk Medisinaldepot",
      dossage: "15 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Norsk Medisinaldepot",
    },
  },
  {
    id: 65,
    title: "Магний 250 мг таблетки 30 шт",
    price: 10.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Швейцария",
      brand: "Novartis",
      dossage: "250 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Novartis",
    },
  },
  {
    id: 66,
    title: "Кальций 500 мг таблетки 30 шт",
    price: 9.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Австрия",
      brand: "Pfizer",
      dossage: "500 мг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Pfizer",
    },
  },
  {
    id: 67,
    title: "Витамин E 400 МЕ капсулы 30 шт",
    price: 15.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Италия",
      brand: "Menarini",
      dossage: "400 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Menarini",
    },
  },
  {
    id: 68,
    title: "Витамин B12 1000 мкг таблетки 30 шт",
    price: 12.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Греция",
      brand: "Pharmathen",
      dossage: "1000 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Pharmathen",
    },
  },
  {
    id: 69,
    title: "Витамин A 10000 МЕ капсулы 30 шт",
    price: 14.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Португалия",
      brand: "Bial",
      dossage: "10000 МЕ",
      releaseForm: "Капсулы",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "2 года",
      isByPrescription: false,
      manufacturer: "Bial",
    },
  },
  {
    id: 70,
    title: "Фолиевая кислота 400 мкг таблетки 30 шт",
    price: 7.0,
    image: "https://placehold.co/215x215/png",
    characteristics: {
      country: "Словакия",
      brand: "Slovakofarma",
      dossage: "400 мкг",
      releaseForm: "Таблетки",
      storageTemperature: "Ниже 25 C",
      quantityPerPackage: 30,
      expirationDate: "3 года",
      isByPrescription: false,
      manufacturer: "Slovakofarma",
    },
  },
];
